### ISSUE TITLE
ionic 3 with Firebase

### ISSUE THREAD

**Issue by AsiaMahmood** [code2gether/livestream-proposals#5]
ِAuthentication and real time database.
plus how to insert, delete and update the data.

**Comment by AhmedAbdulrahman** [comment]
Well, seems to be fun working with Firebase 😄planning to introduce Firestore as well to you all. Inshallah live stream it upcoming weeks

**Comment by AsiaMahmood** [comment]
@AhmedAbdulrahman  Yay awesome  👍 💯
